<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_KONFIRMASI PEMBAYARAN</name>
   <tag></tag>
   <elementGuidId>8b0f0552-4559-443e-9e1e-825697083dfd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/h4</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>2c389d9c-2f98-41d7-b564-7bfcada5c619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KONFIRMASI PEMBAYARAN</value>
      <webElementGuid>ac81d6a0-dd28-40c7-827a-7c50823c0260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/h4[1]</value>
      <webElementGuid>ef153754-9b15-40ef-ae4d-ab344f4a62fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/h4</value>
      <webElementGuid>f2704700-7abc-415d-afd0-9abf0f8a6eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Rekening'])[1]/preceding::h4[1]</value>
      <webElementGuid>f197a34e-4c57-4705-8242-afe9e502db49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Atas Nama'])[1]/preceding::h4[1]</value>
      <webElementGuid>b26e7763-86a4-4699-b9fa-5a765c4af731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KONFIRMASI PEMBAYARAN']/parent::*</value>
      <webElementGuid>63618911-7418-4a27-a793-fcd3337413d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>3e2590c4-a6d5-4c9b-8432-06fe631c5ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'KONFIRMASI PEMBAYARAN' or . = 'KONFIRMASI PEMBAYARAN')]</value>
      <webElementGuid>226146af-adfd-4945-a8f6-6ce559657cc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
