<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rp. 15,000 ,-_kurirx</name>
   <tag></tag>
   <elementGuidId>f091d92e-5040-4a84-a7cc-a4f1c812a552</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='kurirx']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;kurirx&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a57e32b5-573c-41c3-b12d-f8ed272e82cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>fd5dd286-a8ec-41ea-b0b9-257ad5e4544a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kurirx</value>
      <webElementGuid>457ceed1-d372-4263-b447-193cf5c0620c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pilih-kurir</value>
      <webElementGuid>2adad487-a703-4114-bb39-cc7f0cc4626a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>kurir</name>
      <type>Main</type>
      <value>Pos Indonesia</value>
      <webElementGuid>73c5fada-0159-44c8-9e5f-2fad2ede922a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>service</name>
      <type>Main</type>
      <value>Pos Reguler</value>
      <webElementGuid>c45bf999-a4e5-4ca5-8c8d-8f9782f9db57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>harga</name>
      <type>Main</type>
      <value>15000</value>
      <webElementGuid>26f161f7-de62-4623-8ba0-6d7a90af3a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b5255026-b100-4df2-87d3-c9b0584f3218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ongkir&quot;)/table[@class=&quot;table table-bordered&quot;]/tbody[1]/tr[2]/td[@class=&quot;text-center&quot;]/input[@class=&quot;pilih-kurir&quot;]</value>
      <webElementGuid>92b5bb28-4fb2-4583-a887-0094ccf600b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='kurirx']</value>
      <webElementGuid>07d2494f-c932-4142-8cd0-3c944cbdcba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ongkir']/table/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>a542889b-f1df-4cac-a100-3a760569d4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>43c97228-e6f3-4db6-905e-76b7b7d5c8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'kurirx']</value>
      <webElementGuid>6280c3de-c3b9-4a5a-b289-29d8629b89fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
