<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_- Pilih Kabupaten  Kota -BandungBand_f7705e</name>
   <tag></tag>
   <elementGuidId>e826d5cc-c820-4a53-8484-744acbe368be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='kabupaten']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#kabupaten</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>89fe0634-505b-48e6-9c83-23a36d608c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kabupaten</value>
      <webElementGuid>b6df38d8-cc07-4466-9d3f-134f4bf00511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kabupaten</value>
      <webElementGuid>40aebbe6-008d-4a72-993a-f4367aabc2d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>084da9d7-3c5f-4642-b0b4-713a3dc89477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- Pilih Kabupaten / Kota -BandungBandungBandung BaratBanjarBekasiBekasiBogorBogorCiamisCianjurCimahiCirebonCirebonDepokGarutIndramayuKarawangKuninganMajalengkaPangandaranPurwakartaSubangSukabumiSukabumiSumedangTasikmalayaTasikmalaya</value>
      <webElementGuid>e32af859-008c-4d59-bde0-c924123f0672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kabupaten&quot;)</value>
      <webElementGuid>1e36c568-c02c-49ac-9ab6-3dbed1b4c976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='kabupaten']</value>
      <webElementGuid>3c5266bf-cc11-41a9-aebe-12a15854d36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kabupaten'])[1]/following::select[1]</value>
      <webElementGuid>9f0a410a-aa64-4ab4-8283-6f5943e9d8c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provinsi Tujuan'])[1]/following::select[2]</value>
      <webElementGuid>f930d49c-f47d-4e7e-af7a-8de412362c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali Ke Keranjang'])[1]/preceding::select[1]</value>
      <webElementGuid>1c40c0d2-e1fb-4fc7-9c14-8ce8b8e2f708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/preceding::select[1]</value>
      <webElementGuid>0a42193a-aaa0-413c-af88-b511ab3048c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/select</value>
      <webElementGuid>54eee3d6-3dbb-46c1-a38d-17fb8afa3c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'kabupaten' and @name = 'kabupaten' and (text() = '- Pilih Kabupaten / Kota -BandungBandungBandung BaratBanjarBekasiBekasiBogorBogorCiamisCianjurCimahiCirebonCirebonDepokGarutIndramayuKarawangKuninganMajalengkaPangandaranPurwakartaSubangSukabumiSukabumiSumedangTasikmalayaTasikmalaya' or . = '- Pilih Kabupaten / Kota -BandungBandungBandung BaratBanjarBekasiBekasiBogorBogorCiamisCianjurCimahiCirebonCirebonDepokGarutIndramayuKarawangKuninganMajalengkaPangandaranPurwakartaSubangSukabumiSukabumiSumedangTasikmalayaTasikmalaya')]</value>
      <webElementGuid>910f3b50-8b0f-4e94-9ff3-1a72a89d8674</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
