<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Find your account and log in</name>
   <tag></tag>
   <elementGuidId>d1b180df-d15a-470c-8528-99eebde4ac52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a07dfcf2-e3ac-41ca-a20c-8b7fad219ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://facebook.com/login/identify/</value>
      <webElementGuid>e2a7d2fc-9727-4e45-b9a1-9c0f1e36f8cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find your account and log in.</value>
      <webElementGuid>9a0c7e5e-19bc-4126-8b91-64c831530904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_container&quot;)/div[@class=&quot;_9ay7&quot;]/a[1]</value>
      <webElementGuid>d8e028f9-4fa7-487d-ab6a-830408035591</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='email_container']/div[2]/a</value>
      <webElementGuid>6a19dcdc-6bcf-4fac-a030-2d23b367fc25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Find your account and log in.')]</value>
      <webElementGuid>6f623bdb-c5a0-48ea-9daa-1ecd51c6a3d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in to Facebook'])[2]/following::a[1]</value>
      <webElementGuid>100cb30c-4825-4def-8851-81e366f9918b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in'])[1]/preceding::a[2]</value>
      <webElementGuid>74a99e14-e898-4b5e-84a7-dc8da45fec87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/preceding::a[2]</value>
      <webElementGuid>81d3a1de-b454-45a4-8582-750738a02048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find your account and log in.']/parent::*</value>
      <webElementGuid>bd6a47a3-4a49-4492-aa4b-6c95b8d6b4e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://facebook.com/login/identify/')]</value>
      <webElementGuid>e271bff2-3579-4e6f-8533-1eee32d6f69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>1954e3c8-dd9c-4d23-857b-561b6b74a2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://facebook.com/login/identify/' and (text() = 'Find your account and log in.' or . = 'Find your account and log in.')]</value>
      <webElementGuid>1f353d41-e5d6-43c6-b3da-9b191020b19a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
