<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Lengkap_alamat</name>
   <tag></tag>
   <elementGuidId>730c26b3-c971-458a-912d-3bc499d437cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='alamat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;alamat&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>105098e7-7a73-46c2-95e2-628e7ed58c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e131a65d-95c2-46f1-9ee6-f9b4646f020e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89cdb422-5b03-4ab2-8d9c-05f899bb6054</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4e4768c0-7694-4f35-8c93-8f39d5cad94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>alamat</value>
      <webElementGuid>5a6909f9-714e-4f7c-9edb-5c4604e0168b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Masukkan alamat lengkap ..</value>
      <webElementGuid>ebfa679f-5e0d-4e3e-99dc-0f3a2a112f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;section&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;order-summary clearfix&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-6 col-lg-offset-3&quot;]/form[1]/div[@class=&quot;form-group&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>4594f915-59a0-4312-8e03-4687a060aee3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='alamat']</value>
      <webElementGuid>770ef8dc-9c79-40ef-87e5-1b075d7c97fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>f2ac5ddf-8b0b-4d56-8c03-89e97444a4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'alamat' and @placeholder = 'Masukkan alamat lengkap ..']</value>
      <webElementGuid>870bd187-25c4-4b77-b3ed-a1de66753581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
