<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Halo, Selamat Datang</name>
   <tag></tag>
   <elementGuidId>0d2d55a4-66be-44a6-afde-876ec5ddb1da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store']/div/div/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Halo, Selamat Datang!' or . = 'Halo, Selamat Datang!')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>8abbbdb3-309e-4c2e-88cf-ff1a5c966120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Halo, Selamat Datang!</value>
      <webElementGuid>b460c1d0-5f90-454b-9280-cf3392107514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12&quot;]/h5[1]</value>
      <webElementGuid>1ee9dabc-6011-4073-bc10-2da89de2be54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store']/div/div/h5</value>
      <webElementGuid>0b737217-a7d5-4604-99e1-400643b37870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DASHBOARD'])[1]/following::h5[1]</value>
      <webElementGuid>8fbbce3e-fc57-491c-b337-2029fa172216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::h5[1]</value>
      <webElementGuid>1fe875f9-b410-4290-82f4-39b25feabea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Test'])[2]/preceding::h5[1]</value>
      <webElementGuid>c882f5de-1d8b-42b3-912c-b2ea88863362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Halo, Selamat Datang!']/parent::*</value>
      <webElementGuid>6f91ae58-4238-472c-9e4f-00c132113c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>85381d6a-4344-4527-8f16-4abee16fe60d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Halo, Selamat Datang!' or . = 'Halo, Selamat Datang!')]</value>
      <webElementGuid>aa7e00bd-9676-49a3-b7e2-0ed17b14589f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
