<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Baju</name>
   <tag></tag>
   <elementGuidId>33d0b979-529d-4302-acdd-f187e8f7ccef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='responsive-nav']/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0a0b6f22-9938-432e-b73a-05bc5293907b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>produk_kategori.php?id=3</value>
      <webElementGuid>c3ecc1c1-e92a-42d7-a855-4c7f48c2e14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baju</value>
      <webElementGuid>60d5cd59-a9fd-44a8-b91b-3074a2327011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsive-nav&quot;)/div[@class=&quot;category-nav show-on-click&quot;]/ul[@class=&quot;category-list open&quot;]/li[2]/a[1]</value>
      <webElementGuid>e2d57e3d-238e-49f6-9e4e-32b7a5b1fce7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responsive-nav']/div/ul/li[2]/a</value>
      <webElementGuid>21c2be3d-9999-4a78-9807-afdd11b7947b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Baju')]</value>
      <webElementGuid>32687017-4720-45b6-b508-bd6638a62237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Berkategori'])[1]/following::a[1]</value>
      <webElementGuid>3f1474d6-27a6-427c-953e-ce0e74a99fc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kategori Produk'])[1]/following::a[2]</value>
      <webElementGuid>60c0310e-df65-4630-a1b4-3681885bc372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Celana'])[1]/preceding::a[1]</value>
      <webElementGuid>47f43e67-e6b2-43f4-adbb-70cd73dcbe5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tas Selempang'])[1]/preceding::a[2]</value>
      <webElementGuid>c8caf5c4-caf7-4b7e-8b7d-6f4ce6962adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Baju']/parent::*</value>
      <webElementGuid>7c8a9025-d129-4782-84d7-cb620869d8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'produk_kategori.php?id=3')]</value>
      <webElementGuid>32682d69-a9da-4591-8918-c6b45b4b0b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>c2db408d-dfa4-42e9-883a-29278b279694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'produk_kategori.php?id=3' and (text() = 'Baju' or . = 'Baju')]</value>
      <webElementGuid>8ec68546-f587-43f8-ba4a-d264caa41c88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
