<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Celana</name>
   <tag></tag>
   <elementGuidId>2c6c6c7e-7ab6-4c64-baed-b94848d042fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='responsive-nav']/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b9fb406-d06b-44d4-83cb-3d5757619dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>produk_kategori.php?id=4</value>
      <webElementGuid>af440a51-eda4-47db-a041-39848c94fe0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Celana</value>
      <webElementGuid>730c80b0-9c2c-4289-a391-b5741c8f6018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;responsive-nav&quot;)/div[@class=&quot;category-nav show-on-click&quot;]/ul[@class=&quot;category-list open&quot;]/li[3]/a[1]</value>
      <webElementGuid>aebecbff-4bdd-4d27-82f1-df2ec7bed9f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='responsive-nav']/div/ul/li[3]/a</value>
      <webElementGuid>5a315bd4-cbc3-4fe5-b3d7-7f9fdb513c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Celana')]</value>
      <webElementGuid>d60356de-695a-45fc-b8a0-8af92f8b9ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju'])[1]/following::a[1]</value>
      <webElementGuid>0e4ae1ba-c0fd-4678-b108-f8a65f8877fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tidak Berkategori'])[1]/following::a[2]</value>
      <webElementGuid>d03c557a-aa27-4f81-beba-3eec65eb4bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tas Selempang'])[1]/preceding::a[1]</value>
      <webElementGuid>9ac58036-b6b1-47fd-a07e-9db42cce4efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sepatu'])[1]/preceding::a[2]</value>
      <webElementGuid>c9e176fd-8fe9-41b7-b89e-77d50962e7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Celana']/parent::*</value>
      <webElementGuid>5485afff-8c3a-4b4e-a03c-0a14b1cb0d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'produk_kategori.php?id=4')]</value>
      <webElementGuid>a1565a3a-49cb-4c36-8874-53336b01958a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>1b6109b8-5a32-4453-a103-dd09d4daadfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'produk_kategori.php?id=4' and (text() = 'Celana' or . = 'Celana')]</value>
      <webElementGuid>1ee88de7-2242-4a3d-a2f8-4f13561138c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
