<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lihat</name>
   <tag></tag>
   <elementGuidId>8e4a9d9d-8962-48c6-9009-ad585d930777</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store']/div/div/div/div[2]/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.main-btn.btn-block.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dd8564f4-d854-466d-976d-08dc10053c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-btn btn-block text-center</value>
      <webElementGuid>197906b2-8874-43f5-a394-c1c16d381024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>produk_detail.php?id=13</value>
      <webElementGuid>4830e7d5-4155-413d-b8fb-49c833d411f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lihat</value>
      <webElementGuid>9f89471d-6e2d-4c77-9384-7cd67e2353cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-6 col-xs-6&quot;]/div[@class=&quot;product product-single&quot;]/div[@class=&quot;product-body&quot;]/div[@class=&quot;product-btns&quot;]/a[@class=&quot;main-btn btn-block text-center&quot;]</value>
      <webElementGuid>e4dc950a-a6a4-41ac-9e0b-c252bd05c332</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store']/div/div/div/div[2]/div[2]/a</value>
      <webElementGuid>db816bfa-c532-458e-afcb-c6cf2f35d754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lihat')]</value>
      <webElementGuid>042b548c-7f8f-4110-a129-51cb55f047cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju daster bahan tenun'])[1]/following::a[1]</value>
      <webElementGuid>87dc6a6d-39fd-4b1b-90bf-1a27a01e0408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp. 130,000,-'])[1]/following::a[2]</value>
      <webElementGuid>791fa6d1-08ab-4287-a962-4159612335fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan Keranjang'])[1]/preceding::a[1]</value>
      <webElementGuid>b12fa522-ca93-4344-a10d-4cd0a26fd10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju'])[3]/preceding::a[2]</value>
      <webElementGuid>98ab2196-f998-4633-8d19-86d54039859b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lihat']/parent::*</value>
      <webElementGuid>c8131ef1-ab7e-4d78-a872-1d70e30565a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'produk_detail.php?id=13')])[3]</value>
      <webElementGuid>b32d7fc9-c6e6-4870-a555-c6831a978a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a</value>
      <webElementGuid>8fcf96c0-b7ea-439e-9f0d-95e41d1a784b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'produk_detail.php?id=13' and (text() = ' Lihat' or . = ' Lihat')]</value>
      <webElementGuid>c31420d4-5b84-4b36-b48d-9ba5c4ba28e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
