<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masukkan Keranjang</name>
   <tag></tag>
   <elementGuidId>412d0e34-b773-40bd-967d-135043d63343</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='store']/div/div/div/div[2]/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.primary-btn.add-to-cart.btn-block.text-center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c601cea-59a4-44b2-bd4d-ab9265838585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>primary-btn add-to-cart btn-block text-center</value>
      <webElementGuid>18b0084b-346e-4b93-bc76-4845a5de43d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>keranjang_masukkan.php?id=13&amp;redirect=index</value>
      <webElementGuid>97fdb43f-830f-4d75-9f50-be7867875b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Masukkan Keranjang</value>
      <webElementGuid>c032d7af-8e24-4033-b59d-b4622c264752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-3 col-sm-6 col-xs-6&quot;]/div[@class=&quot;product product-single&quot;]/div[@class=&quot;product-body&quot;]/div[@class=&quot;product-btns&quot;]/a[@class=&quot;primary-btn add-to-cart btn-block text-center&quot;]</value>
      <webElementGuid>33a07bd3-c2e4-44ef-88c4-169bbeffddf6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='store']/div/div/div/div[2]/div[2]/a[2]</value>
      <webElementGuid>320cfe17-4aa6-41d0-98d5-2741c4205ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Masukkan Keranjang')]</value>
      <webElementGuid>6d5e6f16-1d47-403f-8e85-441d4e9e8ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat'])[1]/following::a[1]</value>
      <webElementGuid>ed108fa5-a19f-4de8-9f20-34bd5f06e9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju daster bahan tenun'])[1]/following::a[2]</value>
      <webElementGuid>751a3e44-9407-4a8b-b11f-c3fbe15fdf3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Baju'])[3]/preceding::a[1]</value>
      <webElementGuid>4471b28d-333c-494c-b0fc-636fb79212de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quick view'])[2]/preceding::a[1]</value>
      <webElementGuid>71145256-4475-443e-a411-9fe583437d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Masukkan Keranjang']/parent::*</value>
      <webElementGuid>075423d4-876c-42f6-9df8-36a375339f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'keranjang_masukkan.php?id=13&amp;redirect=index')]</value>
      <webElementGuid>972f383f-71b0-4dae-9c31-66227dd0d7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/a[2]</value>
      <webElementGuid>bc991812-01bb-43ba-8b2b-27aa9950bfed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'keranjang_masukkan.php?id=13&amp;redirect=index' and (text() = ' Masukkan Keranjang' or . = ' Masukkan Keranjang')]</value>
      <webElementGuid>5babb06e-86fb-4832-8b69-85f0b77d9d64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
